#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d Terminal Web Media Hobbies Desktop #I II III IV V VI VII VIII IX X


bspc config border_width        2 
bspc config window_gap          4
bspc config top_padding         5
bspc config bottom_padding      5
bspc config left_padding        5
bspc config right_padding       5

bspc config focused_border_color "#1e66f5"
bspc config normal_border_color "#cdd6f4"

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config border_radius        12 
bspc config border_antialias     true

bspc rule -a Gimp desktop='^4' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a Librewolf desktop='^2'
bspc rule -a Firefox desktop='^2'
bspc rule -a "Google-chrome" desktop='^2'
bspc rule -a TelegramDesktop desktop='^3' state=floating
bspc rule -a Krita desktop='^4' follow=on
bspc rule -a Lxappearance state=floating
bspc rule -a Conky-manager2 state=floating
bdpc rule -a vlc desktop='^3' follow=on
bspc rule -a mpv desktop='^3' follow=on
#bspc rule -a mpv state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off
#bspc rule -a TelegramDesktop state=floating
bspc rule -a conky state=floating border=off
#bspc rule -a blueman-manager state=floating
#bspc rule -a Xfce4-terminal border=off 
bspc rule -a Sakura state=floating
bspc rule -a Xterm state=floating

killall conky &

Killall picom &

exec ~/scripts/xrandr125.sh &

exec ~/mypolybar.sh &

exec xrdb -merge ~/.Xresources &

exec xsetroot -cursor_name left_ptr &
